name: "CredSweeper action"
description: "CredSweeper checks files"
author: "r.babenko@samsung.com"
branding:
  icon: "terminal"
  color: "gray-dark"
inputs:
  python_version:
    description: "Python Version. 3.10 - default"
    default: "3.10"
    required: false
  path:
    description: "Path to scan"
    required: true
  report:
    description: "CredSweeper report in JSON format"
    default: "output.json"
    required: false
  args:
    description: "CredSweeper auxiliary arguments"
    default: "--banner --log INFO"
    required: false
runs:
  using: "composite"
  steps:
    - id: setup-python
      name: Setup Python
      uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0 - 2025.01.28
      with:
        python-version: ${{ inputs.python_version }}
    - id: credsweeper-install
      name: Install CredSweeper
      shell: bash
      run: python -m pip install credsweeper
    - id: credsweeper-run
      name: CredSweeper run
      shell: bash
      run: python -m credsweeper ${{ inputs.args }} --path ${{ inputs.path }} --save-json ${{ inputs.report }}
    - id: check-output
      name: Check output
      shell: bash
      run: python -c "import json; import sys; sys.exit(1 if json.load(open('${{ inputs.report }}')) else 0)"
