name: "CredSweeper action"
description: "CredSweeper checks files"
author: "r.babenko@samsung.com"
branding:
  icon: "terminal"
  color: "gray-dark"
inputs:
  python_version:
    description: "Python Version. 3.10 - default"
    default: "3.10"
    required: false
  path:
    description: "Path to scan"
    required: true
  report:
    description: "CredSweeper report in JSON format"
    default: "output.json"
    required: false
  hashed:
    description: "Report output is hashed by default"
    default: "--hashed"
    required: false
  error:
    description: "Exit with an error code if credentials are detected"
    default: "--error"
    required: false
runs:
  using: "composite"
  steps:
    - name: DEBUG
      shell: bash
      env:
        path: ${{ inputs.path }}
        report: ${{ inputs.report }}
        error: ${{ inputs.error }}
        hashed: ${{ inputs.hashed }}
      run: echo "print ('@@@ $error @@@ $report @@@ $path @@@ $PATH @@@')"

    - name: Setup Python
      uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0 - 2025.01.28
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install CredSweeper
      shell: bash
      run: python -m pip install credsweeper

    - name: Run CredSweeper
      shell: bash
      env:
        path: ${{ inputs.path }}
        report: ${{ inputs.report }}
        error: ${{ inputs.error }}
        hashed: ${{ inputs.hashed }}
      run: python -m credsweeper --banner --log INFO --no-color --no-stdout "$error" "$hashed" --save-json "$report" --path "$path"
