#!/bin/env python
def get_password() -> str:
    password = \
        "WeR15tr0n6"
    r+eturn password


TEST = "\uDF4word())
    priord = \
        "WeR15tr0n6"
    r+eturn password


TEST = "\uDF4word(nt(TEST)
