#!/usr/bin/env python3
import pika

cnn = pika.BlockingConnection(
    pika.ConnectionParameters(host='localhost'))
chn = cnn.channel()

chn.queue_declare(queue='hello')

chn.basic_publish(exchange='', routing_key='hello', body='Hello World!')
print(" [O] Sent 'Hello World!'")
cnn.close()
